# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('registration_number', models.IntegerField()),
                ('color', models.CharField(choices=[('bscs', 'BSCS'), ('bsse', 'BSSE'), ('beee', 'BEEE'), ('bece', 'BECE'), ('pharmD', 'PharmD')], max_length=6)),
                ('year_semester', models.CharField(max_length=200)),
                ('occupation', models.CharField(choices=[('student', 'STUDNENT'), ('job', 'JOB'), ('business', 'BUSINESS')], max_length=200)),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
    ]
