# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='color',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='alumni',
            old_name='fullName',
            new_name='full_Name',
        ),
    ]
