# Generated by Django 2.0 on 2018-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abasyntest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.IntegerField()),
                ('auictest', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'abasyntest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('addresstwo', models.CharField(max_length=255)),
                ('citytwo', models.CharField(max_length=30)),
                ('phonetwo', models.CharField(max_length=255)),
                ('addressthree', models.CharField(max_length=255)),
                ('citythree', models.CharField(max_length=30)),
                ('phonethree', models.CharField(max_length=255)),
                ('fathermob', models.CharField(max_length=255)),
                ('activem', models.CharField(max_length=10)),
                ('activef', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('adminid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'adminlogin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admissiondate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stmh', models.CharField(max_length=100)),
                ('stda', models.CharField(max_length=100)),
                ('styr', models.CharField(max_length=100)),
                ('edmh', models.CharField(max_length=100)),
                ('eddt', models.CharField(max_length=100)),
                ('edyr', models.CharField(max_length=100)),
                ('tmh', models.CharField(max_length=100)),
                ('tda', models.CharField(max_length=100)),
                ('tyr', models.CharField(max_length=100)),
                ('adon', models.IntegerField()),
                ('adoff', models.IntegerField()),
            ],
            options={
                'db_table': 'admissiondate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admitcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
                ('yr', models.IntegerField()),
                ('sthr', models.IntegerField()),
                ('stmt', models.IntegerField()),
                ('edhr', models.IntegerField()),
                ('edmt', models.IntegerField()),
            ],
            options={
                'db_table': 'admitcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('submit', models.IntegerField()),
                ('fnam', models.CharField(max_length=100)),
                ('snam', models.CharField(max_length=100)),
                ('mcod', models.IntegerField()),
                ('mnum', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationBsc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bseged', models.CharField(max_length=255)),
                ('bseyr', models.IntegerField()),
                ('bseuni', models.CharField(max_length=255)),
                ('bsesub', models.CharField(max_length=255)),
                ('bsetocgpa', models.CharField(max_length=255)),
                ('bseobt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'education_bsc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationFsc',
            fields=[
                ('fsc_id', models.AutoField(primary_key=True, serialize=False)),
                ('waiting', models.CharField(max_length=20)),
                ('fsedeg', models.CharField(max_length=255)),
                ('fseyr', models.IntegerField()),
                ('fsebod', models.CharField(max_length=255)),
                ('fsesub', models.CharField(max_length=255)),
                ('fsetono', models.IntegerField()),
                ('fseobno', models.IntegerField()),
            ],
            options={
                'db_table': 'education_fsc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationMatric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('yearpass', models.IntegerField()),
                ('board', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('totalmark', models.IntegerField()),
                ('obtainmark', models.IntegerField()),
            ],
            options={
                'db_table': 'education_matric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msdeg', models.CharField(max_length=255)),
                ('msyr', models.IntegerField()),
                ('msnui', models.CharField(max_length=255)),
                ('mssub', models.CharField(max_length=255)),
                ('mstocgpa', models.CharField(max_length=255)),
                ('msobcgpa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'education_ms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationPhd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.IntegerField()),
                ('phddeg', models.CharField(max_length=255)),
                ('phdyr', models.IntegerField()),
                ('phduni', models.CharField(max_length=255)),
                ('phdsub', models.CharField(max_length=255)),
                ('phdtocgpa', models.CharField(max_length=255)),
                ('phdobcgpa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'education_phd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ntstest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolno', models.CharField(max_length=50)),
                ('testtype', models.CharField(max_length=255)),
                ('ob_marks', models.CharField(max_length=100)),
                ('month_nts', models.CharField(max_length=100)),
                ('day_nts', models.CharField(max_length=100)),
                ('year_nts', models.CharField(max_length=100)),
                ('nts_resultcard', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ntstest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Otherdeatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.IntegerField()),
                ('hostel', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'otherdeatils',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('fname', models.TextField()),
                ('month', models.TextField()),
                ('day', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gender', models.TextField()),
                ('citizen', models.TextField()),
                ('domicile', models.TextField()),
                ('cnici', models.IntegerField()),
                ('cnicii', models.IntegerField()),
                ('cniciii', models.IntegerField()),
                ('mobcode', models.IntegerField()),
                ('mobnumber', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programone', models.CharField(max_length=100)),
                ('programtwo', models.CharField(max_length=100)),
                ('programthree', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mresult', models.CharField(max_length=255)),
                ('fresult', models.CharField(max_length=255)),
                ('bscresult', models.CharField(max_length=255)),
                ('bsresult', models.CharField(max_length=255)),
                ('msresult', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'resultcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.TextField()),
                ('university', models.TextField()),
                ('firstname', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'signup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalstatus', models.IntegerField()),
                ('address', models.IntegerField()),
                ('education', models.IntegerField()),
                ('metric', models.IntegerField()),
                ('fsc', models.IntegerField()),
                ('bsc', models.IntegerField()),
                ('phd', models.IntegerField()),
                ('metricimg', models.IntegerField()),
                ('fscimg', models.IntegerField()),
                ('bscimg', models.IntegerField()),
                ('bsimg', models.IntegerField()),
                ('nts', models.IntegerField()),
                ('ms', models.IntegerField()),
                ('msimg', models.IntegerField()),
                ('ntscard', models.IntegerField()),
                ('teststatus', models.IntegerField()),
                ('othdetil', models.IntegerField()),
                ('program', models.IntegerField()),
                ('submit', models.IntegerField()),
                ('ntsok', models.IntegerField()),
                ('auictestok', models.IntegerField()),
                ('ntscardok', models.IntegerField()),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'submit',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
