# Generated by Django 2.0 on 2018-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
