# Generated by Django 2.0 on 2018-11-22 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission_sys', '0004_auto_20181121_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='signup',
            table=None,
        ),
    ]
