# Generated by Django 2.0 on 2019-01-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0005_auto_20181121_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('open_date', models.IntegerField()),
                ('close_date', models.IntegerField()),
            ],
            options={
                'db_table': 'admissions',
                'managed': False,
            },
        ),
    ]
