# Generated by Django 2.0 on 2019-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0006_admissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offered_programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('short_name', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'offered_programs',
                'managed': False,
            },
        ),
    ]
