# Generated by Django 2.0 on 2019-05-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0007_offered_programs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'managed': False},
        ),
    ]
