# Generated by Django 2.0 on 2019-05-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0008_auto_20190528_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
