# Generated by Django 2.0 on 2019-04-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0009_auto_20190426_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
