# Generated by Django 2.0 on 2019-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0011_workouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workouts',
        ),
    ]
