# Generated by Django 2.0 on 2019-06-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_sys', '0009_auto_20190528_1511'),
        ('admission_sys', '0012_delete_workouts'),
    ]

    operations = [
    ]
