# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(upload_to='images')),
                ('slider2', models.ImageField(upload_to='images')),
                ('slider3', models.ImageField(upload_to='images')),
            ],
        ),
    ]
