# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=120)),
                ('profile', models.ImageField(upload_to='images')),
            ],
        ),
    ]
