# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20180212_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
