# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embededcode', models.CharField(max_length=400)),
            ],
        ),
    ]
