# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='embededcode',
            field=models.TextField(),
        ),
    ]
