# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_auto_20180213_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('semester', models.CharField(choices=[('1', '2'), ('3', '4'), ('5', '6'), ('7', '8')], max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('credit_hours', models.CharField(max_length=120)),
                ('pre_req', models.CharField(max_length=120)),
            ],
        ),
    ]
