# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='semester',
            field=models.CharField(choices=[('Semester', '1'), ('Semester', '2'), ('Semester', '3'), ('Semester', '4'), ('Semester', '5'), ('Semester', '6'), ('Semester', '7'), ('Semester', '8')], max_length=120),
        ),
    ]
