# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0011_event_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default='computing', max_length=300),
        ),
    ]
