# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0012_auto_20180604_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=120)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
