# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0013_auto_20180625_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acdamic_Calander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
