# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0016_auto_20180903_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Computing', 'Computing'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('life-scienecs', 'Life Scienecs'), ('management-sciences', 'Management Sciences')], default='computing', max_length=300),
        ),
    ]
