# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0019_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='link',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
