# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0020_new_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Online Admission',
                'verbose_name_plural': 'Online Admissions',
            },
        ),
    ]
