# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0021_online_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
