# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0022_auto_20180914_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acdamic_calander',
            options={'verbose_name': 'Acdamic Calander', 'verbose_name_plural': 'Acdamic_Calander'},
        ),
        migrations.AlterModelOptions(
            name='fees',
            options={'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
    ]
