# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0024_auto_20180914_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'CLO',
                'verbose_name_plural': 'CLOs',
            },
        ),
    ]
