# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0026_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableGraduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
