# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0027_timetablegraduate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='downloads')),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.AlterModelOptions(
            name='timetablegraduate',
            options={'verbose_name': 'Timetable Graduate', 'verbose_name_plural': 'Timetable Graduates'},
        ),
    ]
