# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0031_auto_20180922_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acdamic_Calander_Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Acdamic_Calander_Graduate',
                'verbose_name_plural': 'Acdamic_Calander_Graduates',
            },
        ),
    ]
