# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0032_acdamic_calander_graduate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acdamic_calander_graduate',
            options={'verbose_name': 'Acdamic Calander Graduate', 'verbose_name_plural': 'Acdamic Calander Graduates'},
        ),
        migrations.AddField(
            model_name='acdamic_calander_graduate',
            name='visibality',
            field=models.BooleanField(default=False),
        ),
    ]
