# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-29 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0036_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='twiter',
        ),
    ]
