# Generated by Django 2.0 on 2018-12-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0037_remove_staff_twiter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission Letter', 'verbose_name_plural': 'Permission Letters'},
        ),
    ]
