# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField()),
                ('link', models.CharField(default='#', max_length=300)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
