# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ansec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Apply Now',
                'verbose_name_plural': 'Apply Now',
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField()),
                ('link', models.CharField(default='#', max_length=300)),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
            },
        ),
        migrations.CreateModel(
            name='Orgnizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('phone_no', models.IntegerField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Orgnizer',
                'verbose_name_plural': 'Orgnizers',
            },
        ),
    ]
